version: '3'
services:
  app:
    container_name: recipes_app
    build:
      context: .
      dockerfile: config/docker/Dockerfile
    entrypoint: config/docker/entrypoints/app.sh
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - vite
      - db
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      VITE_RUBY_HOST: vite
  vite:
    build: .
    entrypoint: config/docker/entrypoints/vite.sh
    volumes:
      - .:/app
    environment:
      DEBUG: '*vite*'
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
    ports:
      - 3036:3036

  db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: recipes_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  postgres_data:
